##' Convert multivariate skew-t parameters into bivariate
##' 
##' This function converts parameters of a multivariate skew-t distribution
##' into parameters for a bivariate skew-t using formulas from
##' wind_radiosonde_QC_01.pdf (from Mandy).
##' 
##' @param xi Vector of parameters for the skew-t distribution.
##' @param omega matrix of parameters for the skew-t distribution.
##' @param alpha Vector of parameters for the skew-t distribution.
##' @param nu Numeric value of parameter for the skew-t distribution.
##' @param r This function is currently very specific to the 16x16 case.  r
##' specifies which of the 8 distributions you wish to see, and then extracts
##' the (r, r+8) parameters from that distribution.
##' @param alphaAdj If TRUE, computes the correct alpha for the marginal (per
##' Azzalini et.al's "Distributions generated by perturbations of symmetry",
##' page 18 and Capitano et.al's "Graphical models for skew-normal variates",
##' page 15).  If false, just subsets alpha.
##' 
##' @return A list of the 4 parameters of the bivariate skew-t.
##' 
##' @export
##' 

marginal = function( xi, omega, alpha, nu, r=1, alphaAdj=F ){
    #Check data types
    if(!is.numeric(xi))
        stop("xi must be numeric!")
    if(!is(omega,"matrix"))
        stop("omega must be a matrix!")
    if(!is.numeric(alpha))
        stop("alpha must be numeric!")
    if(!is.numeric(nu))
        stop("nu must be numeric!")
    
    #Check data dimensions
    p = length(xi)
    s = 1:p
    s = s[-r]
    if(any(dim(omega)!=p))
        stop("omega must have dimensions pxp, where p=length(xi)!")
    if(length(alpha)!=p)
        stop("alpha must have the same length as xi")
    if(length(nu)!=1)
        stop("nu must have length 1!")
    if(any(!r %in% 1:p))
        stop("All of r's values must be in 1:p!")
    
    xi.r = xi[r]
    omega.r = omega[r,r]
    if(alphaAdj){
        w = diag(sqrt(diag(omega)))
        omega_b = diag(1/diag(w)) %*% omega %*% diag(1/diag(w)) #Note: diag(1/diag(w)) is w^{-1}
        w.r = diag(sqrt(diag(omega.r)))
        B = diag(1/diag(w))%*%omega[,r]
        alpha.r = w.r %*% solve(omega.r) %*% t(B) %*% alpha /
            as.numeric( sqrt(1+t(alpha)%*%(omega_b - B %*% solve(omega.r) %*% t(B)) %*% alpha) )
    } else {
        alpha.r = alpha[r]
    }
    nu.r = nu
    return( list(xi=xi.r, omega=omega.r, alpha=alpha.r, nu=nu.r) )
}
